---
# tasks file for traefik

- name: Create traefik deployment path ({{wordpress.deploy_name}})
  file:
    path: "{{item}}"
    mode: '0700'
    state: directory
  loop:
    - "{{deployment_root_path}}/{{deploy_name}}"
    - "{{deployment_root_path}}/{{deploy_name}}/content/"
    - "{{deployment_root_path}}/{{deploy_name}}/content/mysql/"
    - "{{deployment_root_path}}/{{deploy_name}}/content/wordpress/"

- name: Create Kubernetes templates ({{wordpress.deploy_name}})
  template:
    src: "{{item}}.yml.j2"
    dest: "{{deployment_root_path}}/{{deploy_name}}/{{item}}.yml"
  loop:
    "{{template_files}}"
  register: deployment_changes

- name: Deploy Kubernetes objects ({{wordpress.deploy_name}})
  k8s:
    src: "{{deployment_root_path}}/{{deploy_name}}/{{item}}.yml"
    state: present
  loop:
    "{{template_files}}"
  when: deployment_changes.changed